apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-client
  template:
    metadata:
      labels:
        app: fl-client
    spec:
      containers:
        - name: fl-client
          image: fl-client:latest
          imagePullPolicy: Never